# Gabarito — Matrizes

Este notebook traz a resolução comentada dos exercícios de [`0304a_matrizes.ipynb`](0304a_matrizes.ipynb).

⚠️ **Antes de olhar aqui:** tente resolver os exercícios sozinho no notebook original e use as células de verificação (`assert`) para conferir sua resposta. Volte a este gabarito só depois de tentar — ou se travar de verdade em algum passo.

In [ ]:
# Imports necessarios para os exercicios abaixo.
import numpy as np


## Básico

**Exercício 1.** Dada a matriz F, determine sua ordem, o elemento f₂₃ e classifique-a (quadrada, diagonal, nula ou nenhuma dessas).

In [ ]:
F = np.array([[5, 0, 0], [0, -2, 8], [0, 0, 3]])

# ordem: número de linhas e de colunas de F
ordem_ex1 = F.shape

# f_23 = linha 2, coluna 3 -> índices 1 e 2 em Python
elemento_ex1 = F[1, 2]

# F tem um elemento fora da diagonal principal diferente de zero (8),
# então não é diagonal nem nula, mas é quadrada (3 linhas, 3 colunas)
classificacao_ex1 = "quadrada"

print(ordem_ex1, elemento_ex1, classificacao_ex1)


(3, 3) 8 quadrada


**Exercício 2.** Some as matrizes A e B, e calcule o triplo de A.

In [3]:
A = np.array([[2, -1], [4, 5]])
B = np.array([[1, 3], [-2, 0]])

# soma elemento a elemento
soma_ex2 = A + B

# produto por escalar: multiplica cada elemento por 3
triplo_ex2 = 3 * A

print(soma_ex2)
print(triplo_ex2)


[[3 2]
 [2 5]]
[[ 6 -3]
 [12 15]]


## Intermediário

**Exercício 3.** Verifique se o produto C @ D existe e, se existir, calcule-o.

In [4]:
C = np.array([[1, 0, 2], [-1, 3, 1]])  # ordem 2x3
D = np.array([[3, 1], [2, 1], [1, 0]])  # ordem 3x2

# colunas de C (3) == linhas de D (3) -> produto existe
produto_existe_ex3 = C.shape[1] == D.shape[0]

produto_ex3 = C @ D

print(produto_existe_ex3)
print(produto_ex3)


True
[[5 1]
 [4 2]]


**Exercício 4.** Calcule a transposta de E e diga se E é simétrica.

In [ ]:
E = np.array([[4, 7, -1], [7, 2, 5], [-1, 5, 9]])

transposta_ex4 = E.T

# E é simetrica se E == E^T
eh_simetrica_ex4 = np.array_equal(E, E.T)

print(transposta_ex4)
print(eh_simetrica_ex4)


[[ 4  7 -1]
 [ 7  2  5]
 [-1  5  9]]
True


## Desafio

**Exercício 5.** Aplique a matriz de escala (x2 em x, x0.5 em y) ao ponto (4, 6).

In [6]:
matriz_escala = np.array([[2, 0], [0, 0.5]])
ponto = np.array([[4], [6]])

# produto matriz de escala x ponto (matriz coluna), depois achatado num vetor
ponto_transformado_ex5 = np.ravel(matriz_escala @ ponto)

print(ponto_transformado_ex5)


[8. 3.]


**Exercício 6.** Verifique se G é de fato a inversa de H, checando H @ G contra a identidade.

In [ ]:
H = np.array([[2, 5], [1, 3]])
G = np.array([[3, -5], [-1, 2]])

# G é a inversa de H se H @ G resultar na matriz identidade
g_eh_inversa_de_h_ex6 = np.array_equal(H @ G, np.eye(2, dtype=int))

print(g_eh_inversa_de_h_ex6)


True
