# Gabarito — Determinantes

Este notebook traz a resolução comentada dos exercícios de [`0305a_determinantes.ipynb`](0305a_determinantes.ipynb).

⚠️ **Antes de olhar aqui:** tente resolver os exercícios sozinho no notebook original e use as células de verificação (`assert`) para conferir sua resposta. Volte a este gabarito só depois de tentar — ou se travar de verdade em algum passo.

In [ ]:
# Imports e funções necessárias para os exercícios abaixo (definidas na
# teoria do notebook principal).
import numpy as np


def menor_complementar(matriz: np.ndarray, i: int, j: int) -> float:
    """Determinante da matriz obtida eliminando a linha i e a coluna j de matriz."""
    submatriz = np.delete(np.delete(matriz, i, axis=0), j, axis=1)
    return np.linalg.det(submatriz)


def cofator(matriz: np.ndarray, i: int, j: int) -> float:
    """Complementar algébrico (cofator) do elemento na linha i, coluna j de matriz."""
    return ((-1) ** (i + j)) * menor_complementar(matriz, i, j)


def determinante_por_cofatores(matriz: np.ndarray, linha: int = 0) -> float:
    """Determinante de uma matriz quadrada, expandindo por cofatores ao longo da linha escolhida."""
    n = matriz.shape[0]
    if n == 1:
        return matriz[0, 0]
    total = 0.0
    for coluna in range(n):
        elemento = matriz[linha, coluna]
        if elemento == 0:
            continue
        submatriz = np.delete(np.delete(matriz, linha, axis=0), coluna, axis=1)
        total += elemento * ((-1) ** (linha + coluna)) * determinante_por_cofatores(submatriz)
    return total


def chio(matriz: np.ndarray) -> np.ndarray:
    """Reduz a ordem de uma matriz quadrada em 1 pela Regra de Chió (requer matriz[0, 0] == 1)."""
    n = matriz.shape[0]
    reduzida = np.zeros((n - 1, n - 1))
    for i in range(1, n):
        for j in range(1, n):
            reduzida[i - 1, j - 1] = matriz[i, j] - matriz[i, 0] * matriz[0, j]
    return reduzida

## Básico

**Exercício 1.** Calcule o determinante de F (2×2) e de G (3×3, pela Regra de Sarrus).

In [2]:
F = np.array([[3, 5], [2, 4]])
G = np.array([[1, 0, 2], [3, 1, 1], [2, 4, 0]])

# ordem 2: det = a*d - b*c
det_f_ex1 = F[0, 0] * F[1, 1] - F[0, 1] * F[1, 0]

# ordem 3, Regra de Sarrus: soma as diagonais \, subtrai as diagonais /
a, b, c = G[0]
d, e, f = G[1]
g, h, i = G[2]
det_g_ex1 = (a * e * i + b * f * g + c * d * h) - (c * e * g + a * f * h + b * d * i)

print(det_f_ex1, det_g_ex1)

2 16


**Exercício 2.** Calcule o menor complementar D_23 e o cofator A_23 de H.

In [ ]:
H = np.array([[2, 1, 3], [0, 5, 4], [1, 2, 6]])

# D_23: elimina a linha 2 (índice 1) e a coluna 3 (´ndice 2)
menor_ex2 = menor_complementar(H, 1, 2)

# A_23 = (-1)^(2+3) * D_23
cofator_ex2 = cofator(H, 1, 2)

print(menor_ex2, cofator_ex2)

2.9999999999999996 -2.9999999999999996


## Intermediário

**Exercício 3.** Calcule o determinante de J (4×4) por expansão em cofatores, expandindo pela linha com mais zeros.

In [ ]:
J = np.array([[3, 0, 2, 0], [1, 2, 0, 4], [0, 1, 5, 2], [2, 0, 1, 3]])

# a linha 1 (índice 0) tem dois zeros -> menos termos para somar
det_j_ex3 = determinante_por_cofatores(J, linha=0)

print(det_j_ex3)

96.0


**Exercício 4.** Use a Regra de Chió para reduzir K (4×4, com K[0,0] = 1) a uma matriz 3×3 e calcule seu determinante.

In [5]:
K = np.array([[1, 2, 0, -1], [3, 1, 2, 0], [-2, 0, 1, 3], [1, -1, 2, 1]], dtype=float)

reduzida_ex4 = chio(K)
det_k_ex4 = np.linalg.det(reduzida_ex4)

print(reduzida_ex4)
print(det_k_ex4)

[[-5.  2.  3.]
 [ 4.  1.  1.]
 [-3.  2.  2.]]
11.000000000000002


## Desafio

**Exercício 5.** Calcule a inversa de L (3×3) pela matriz adjunta.

In [6]:
L = np.array([[2, 1, 1], [1, 3, 2], [1, 0, 1]], dtype=float)

# matriz de cofatores de L, depois transposta (adjunta), depois dividida pelo determinante
matriz_cofatores_L = np.array([[cofator(L, i, j) for j in range(3)] for i in range(3)])
adjunta_L = matriz_cofatores_L.T
inversa_ex5 = (1 / np.linalg.det(L)) * adjunta_L

print(inversa_ex5)

[[ 0.75 -0.25 -0.25]
 [ 0.25  0.25 -0.75]
 [-0.75  0.25  1.25]]


**Exercício 6.** Encontre o polinômio de grau 2 que passa por (0, 2), (1, 3) e (3, 17), usando a matriz de Vandermonde.

In [ ]:
xs_ex6 = [0, 1, 3]
ys_ex6 = [2, 3, 17]

# uma linha por ponto, com as potências 0, 1 e 2 de cada x
matriz_v_ex6 = np.array([[x ** potencia for potencia in range(3)] for x in xs_ex6], dtype=float)
coeficientes_ex6 = np.linalg.solve(matriz_v_ex6, ys_ex6)

print(matriz_v_ex6)
print(coeficientes_ex6)

[[1. 0. 0.]
 [1. 1. 1.]
 [1. 3. 9.]]
[ 2. -1.  2.]
