# Gabarito — Sistemas Lineares

Este notebook traz a resolução comentada dos exercícios de [`0306a_sistemas_lineares.ipynb`](0306a_sistemas_lineares.ipynb).

⚠️ **Antes de olhar aqui:** tente resolver os exercícios sozinho no notebook original e use as células de verificação (`assert`) para conferir sua resposta. Volte a este gabarito só depois de tentar — ou se travar de verdade em algum passo.

In [1]:
# Imports necessários para os exercícios abaixo.
import numpy as np

## Básico

**Exercício 1.** Montar a matriz de coeficientes e o vetor de termos independentes do sistema 2x+5y=19, 4x-y=5.

In [ ]:
# cada linha de A e os coeficientes de x e y de uma equação, na ordem dada
A_ex1 = np.array([[2, 5], [4, -1]])
b_ex1 = np.array([19, 5])

print(A_ex1)
print(b_ex1)

[[ 2  5]
 [ 4 -1]]
[19  5]


**Exercício 2.** Resolver por Cramer o sistema 3x+y=11, x+2y=12.

In [2]:
A2 = np.array([[3, 1], [1, 2]])
b2 = np.array([11, 12])

D = np.linalg.det(A2)

A2_x = A2.copy()
A2_x[:, 0] = b2
D_x = np.linalg.det(A2_x)

A2_y = A2.copy()
A2_y[:, 1] = b2
D_y = np.linalg.det(A2_y)

x_ex2 = D_x / D
y_ex2 = D_y / D

print(f"D = {D:.0f}, D_x = {D_x:.0f}, D_y = {D_y:.0f}")
print(x_ex2, y_ex2)

D = 5, D_x = 10, D_y = 25
1.9999999999999993 5.000000000000001


**Exercício 3.** Classificar o sistema (SPD, SPI ou SI) a partir da matriz aumentada já escalonada `[[1,-2,3,5],[0,1,-1,2],[0,0,0,4]]`.

In [3]:
# a última linha representa 0x + 0y + 0z = 4, uma contradição -> não há solução
classificacao_ex3 = "SI"

print(classificacao_ex3)

SI


## Intermediário

**Exercício 4.** Escalonar do zero o sistema x+y+z=6, 2x+y-z=1, x-y+2z=5, e encontrar a solução.

In [4]:
A_ex4 = np.array([[1, 1, 1], [2, 1, -1], [1, -1, 2]], dtype=float)
b_ex4 = np.array([6, 1, 5], dtype=float)

aumentada_ex4 = np.hstack([A_ex4, b_ex4.reshape(-1, 1)])

# L2 -> L2 - 2*L1
aumentada_ex4[1] = aumentada_ex4[1] - 2 * aumentada_ex4[0]
# L3 -> L3 - 1*L1
aumentada_ex4[2] = aumentada_ex4[2] - 1 * aumentada_ex4[0]
# L3 -> L3 - (fator)*L2, para zerar a coluna do meio
fator = aumentada_ex4[2, 1] / aumentada_ex4[1, 1]
aumentada_ex4[2] = aumentada_ex4[2] - fator * aumentada_ex4[1]

print("Matriz escalonada:")
print(aumentada_ex4)

# substituição de trás para frente
z = aumentada_ex4[2, 3] / aumentada_ex4[2, 2]
y = (aumentada_ex4[1, 3] - aumentada_ex4[1, 2] * z) / aumentada_ex4[1, 1]
x = (aumentada_ex4[0, 3] - aumentada_ex4[0, 2] * z - aumentada_ex4[0, 1] * y) / aumentada_ex4[0, 0]

solucao_ex4 = np.array([x, y, z])
print(solucao_ex4)

Matriz escalonada:
[[  1.   1.   1.   6.]
 [  0.  -1.  -3. -11.]
 [  0.   0.   7.  21.]]
[1. 2. 3.]


**Exercício 5.** Calcular a característica de M = [[1,2,3],[2,4,6],[1,0,1]].

In [5]:
M_ex5 = np.array([[1, 2, 3], [2, 4, 6], [1, 0, 1]], dtype=float)

# a linha 2 e exatamente o dobro da linha 1 (L2 -> L2 - 2*L1 zera a linha)
escalonada_ex5 = M_ex5.copy()
escalonada_ex5[1] = escalonada_ex5[1] - 2 * escalonada_ex5[0]
print(escalonada_ex5)

caracteristica_ex5 = np.count_nonzero(np.any(escalonada_ex5 != 0, axis=1))
print(caracteristica_ex5)

[[1. 2. 3.]
 [0. 0. 0.]
 [1. 0. 1.]]
2


**Exercício 6.** Classificar, sem resolver por completo, o sistema A_ex6 x = b_ex6 com A_ex6=[[1,1,1],[2,2,2],[1,-1,0]] e b_ex6=[4,8,1].

In [6]:
A_ex6 = np.array([[1, 1, 1], [2, 2, 2], [1, -1, 0]], dtype=float)
b_ex6 = np.array([4, 8, 1], dtype=float)

posto_a = np.linalg.matrix_rank(A_ex6)
posto_aumentada = np.linalg.matrix_rank(np.hstack([A_ex6, b_ex6.reshape(-1, 1)]))
n = A_ex6.shape[1]
print(f"posto(A) = {posto_a}, posto([A|b]) = {posto_aumentada}, n = {n}")

# posto(A) = posto([A|b]) = 2, menor que n = 3 -> SPI
classificacao_ex6 = "SPI"
print(classificacao_ex6)

posto(A) = 2, posto([A|b]) = 2, n = 3
SPI


## Desafio

**Exercício 7.** Misturar três soluções (10%, 20% e 50% de ácido) para obter 100L a 33% de ácido, com a quantidade de C igual à soma de A e B.

In [7]:
# a+b+c=100 (volume total); 0.10a+0.20b+0.50c=33 (acido total); c=a+b -> a+b-c=0
A_ex7 = np.array([[1, 1, 1], [0.10, 0.20, 0.50], [1, 1, -1]])
b_ex7 = np.array([100, 33, 0])

solucao_ex7 = np.linalg.solve(A_ex7, b_ex7)
print(solucao_ex7)

[20. 30. 50.]


**Exercício 8.** Encontrar uma solução não trivial do sistema homogêneo x+y-z=0, 2x-y+2z=0, 3x+z=0.

In [8]:
A_ex8 = np.array([[1, 1, -1], [2, -1, 2], [3, 0, 1]], dtype=float)

# da 1a equação: z = x + y
# substituindo na 2a: 2x - y + 2(x+y) = 0 -> 4x + y = 0 -> y = -4x
# então z = x + y = x - 4x = -3x
# tomando x = 1, o vetor direção e (1, -4, -3); a 3a equação (3x+z=0) e combinação das outras duas
vetor_solucao_ex8 = np.array([1, -4, -3], dtype=float)

print(vetor_solucao_ex8)
print("Conferindo A @ v =", A_ex8 @ vetor_solucao_ex8)

[ 1. -4. -3.]
Conferindo A @ v = [0. 0. 0.]
